### ISSUE TITLE
Getting warning on EventDatabase.create(props)

### ISSUE THREAD

**Issue by Necriso** [dflourusso/expo-sqlite-orm#18]
> 
        const props = {
            id: 1,
            eventcity: "TestCity",
            eventlocation: "TestLocation",
            eventname: "TestEvent",
        };
        await EventDatabase.create(props)
    

After that I get "Possible Unhandled Promise Rejection (id: 0): Object {}"

But the data is in the database and can be get with EventDatabase.query(options).

What can I do to get rid off this warning?

**Comment by timmytune** [comment]
I am also having this issue, how does one get rid of the warning ?

**Comment by DennisStudent** [comment]
Same here

**Comment by dflourusso** [comment]
Which expo sdk version are you using?

**Comment by timmytune** [comment]
3.8.0

**Comment by dflourusso** [comment]
> 3.8.0

What about the **expo sdk version**?

Are you using 35?

**Comment by timmytune** [comment]
yes it is 35

**Comment by dflourusso** [comment]
Provide a demo with a snack link please

**Comment by SomnathKadam** [comment]
for expo cli version 3.11.3 import * as SQLite from 'expo-sqlite';

**Comment by dflourusso** [comment]
Thats it @SomnathKadam 
thanks

**Comment by lucasvieceli** [comment]
expo-cli : 3.23.3


error: Possible Unhandled Promise Rejection (id: 14):
