### ISSUE TITLE
bulkInsertOrReplace failing silently?

### ISSUE THREAD

**Issue by auc0le** [dflourusso/expo-sqlite-orm#19]
Hello,

When trying to insert an array of 257 objects via the bulkInsertOrReplace method, it fails without providing any error messages.

Is there a limit on how many items can be inserted? Is there a way to get more error messages?

The promise and/or error blocks do not run:
await databaseLayer.bulkInsertOrReplace(contactDataToSave).then(response => {
            console.log('Back from Contact save, now on to Meta Data Save.');
            console.log(response);
        }).catch(err => console.error('Error saving metadata ' + err))

**Comment by dflourusso** [comment]
Hello, 
I don't know about limitations, but it shouldn't throw any errors.
For while you can try to paginate your `bulkInsert`.

**Comment by dflourusso** [comment]
Could you provide an example in https://snack.expo.io?
