### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by johnvalle** [dflourusso/expo-sqlite-orm#37]
Hi! Can we add a typescript support for this? It would be really nice! I would be more than willing to help

**Comment by dflourusso** [comment]
Hi, i need to add typescript supports and some react hooks adjustments, but i'm out of time for while.

**Comment by sstephans** [comment]
Any progress on this?

**Comment by dflourusso** [comment]
Hello, good news

I started today adding typescript support. It will take some time to be ready yet, but i'm working on.
I'm thinking about convert it to react-hooks concept and the release the [expo-sqlite-orm v2](https://github.com/dflourusso/expo-sqlite-orm/tree/feature/v2)

**Comment by sstephans** [comment]
Let me know if you need a hand converting to functional components and hooks. I've done a fair bit of work in that area.

**Comment by johnvalle** [comment]
That's great news! I can also help with the hooks and typescript support.

**Comment by realjjaveweb** [comment]
How is the realease of the feature/v2 looking please?

**Comment by dflourusso** [comment]
The v2 has already typescript and migrations support.

Currently it's on [alpha 5](https://www.npmjs.com/package/expo-sqlite-orm/v/2.0.0-alpha-5) version

**Comment by dflourusso** [comment]
Hello, V2 is live now!!!
