### ISSUE TITLE
Cannot find native module 'ExpoSQLite'

### ISSUE THREAD

**Issue by FelipeBohnertPaetzold** [dflourusso/expo-sqlite-orm#64]
After upgrade to expo sdk 49, when importing any attribute from expo-sqlite-orm the testing library throws  "Cannot find native module 'ExpoSQLite'"

![image](https://github.com/dflourusso/expo-sqlite-orm/assets/15256199/623fd713-31c9-4c80-b35d-4b4e00661211)

**Comment by dflourusso** [comment]
I don't know what is happening exactly, but looks like this problem is happening on your project @FelipeBohnertPaetzold .

I created a new project from scratch here to test and everything is working fine.

**Comment by garygcchiu** [comment]
@FelipeBohnertPaetzold you will need to rebuild your dev client. `cd` into your `expo` directory and run `expo run:ios` or `eas build`.
